"""Bootstrap must provision template/.venv from the tracked uv project.

Regression guard: the venv used by bootstrap, doctor, and the test suite is
generated by ``uv sync --locked --group dev``. Nothing else may build it
ad-hoc, and every third-party module imported by template code must be a
declared dependency so the lock reproduces the working environment.
"""

from __future__ import annotations

import os
import re
import subprocess
import tomllib
from pathlib import Path

import pytest

from helpers import TEMPLATE


ROOT = Path(TEMPLATE)

# import name -> distribution name for third-party modules imported by template code
THIRD_PARTY_IMPORTS = {
    "yaml": "pyyaml",
    "jsonschema": "jsonschema",
    "openai": "openai",
    "chinese_calendar": "chinese-calendar",
}

VENV_PYTHON = ROOT / ".venv" / "bin" / "python"
SYNC_COMMAND = "uv sync --locked --group dev"


def requirement_name(spec: str) -> str:
    return re.split(r"[<>=!~\[; ]", spec, maxsplit=1)[0].strip().lower()


def declared_dependencies() -> dict[str, str]:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return {requirement_name(spec): spec for spec in data["project"]["dependencies"]}


def test_pyproject_declares_every_third_party_import():
    declared = declared_dependencies()
    missing = {imp: req for imp, req in THIRD_PARTY_IMPORTS.items() if req not in declared}

    assert not missing, f"pyproject.toml missing dependencies for imports: {missing}"


def test_uv_lock_covers_declared_third_party_imports():
    lock = (ROOT / "uv.lock").read_text(encoding="utf-8")

    for distribution in THIRD_PARTY_IMPORTS.values():
        assert f'name = "{distribution}"' in lock, f"uv.lock missing locked package: {distribution}"


def test_setup_script_runs_locked_dev_sync():
    script = ROOT / "scripts" / "setup-python-venv.sh"

    assert script.exists(), "scripts/setup-python-venv.sh must exist"
    assert os.access(script, os.X_OK), "scripts/setup-python-venv.sh must be executable"

    invocations = [line.strip() for line in script.read_text(encoding="utf-8").splitlines()]
    assert any(line.startswith(SYNC_COMMAND) for line in invocations), (
        f"setup script must invoke `{SYNC_COMMAND}`"
    )


def test_python_version_pin_matches_ci():
    pinned = (ROOT / ".python-version").read_text(encoding="utf-8").strip()
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    assert pinned, ".python-version must pin an interpreter for a reproducible venv"
    assert f'python-version: "{pinned}"' in workflow


def test_installer_provisions_venv_after_brew_bundle():
    installer = (ROOT / "install.sh").read_text(encoding="utf-8")

    assert '"$DIR/scripts/setup-python-venv.sh"' in installer
    assert installer.index("brew-bundle.sh") < installer.index("setup-python-venv.sh")


def test_venv_interpreter_matches_pin():
    if not VENV_PYTHON.exists():
        pytest.skip("template/.venv not provisioned in this checkout")

    pinned = (ROOT / ".python-version").read_text(encoding="utf-8").strip()
    result = subprocess.run(
        [str(VENV_PYTHON), "-c", "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == pinned


def test_venv_resolves_third_party_imports():
    if not VENV_PYTHON.exists():
        pytest.skip("template/.venv not provisioned in this checkout")

    for module in THIRD_PARTY_IMPORTS:
        result = subprocess.run(
            [str(VENV_PYTHON), "-c", f"import {module}"],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, f"import {module} failed in template/.venv: {result.stderr}"
