#!/usr/bin/env bash

run() {
  if [ "${DRY_RUN:-0}" -eq 1 ]; then
    printf 'DRY-RUN:'; printf ' %q' "$@"; printf '\n'
  else
    "$@"
  fi
}

try_run() {
  if ! run "$@"; then
    echo "warn: command failed:"; printf '  %q' "$@"; printf '\n'
  fi
}

have() { command -v "$1" >/dev/null 2>&1; }

capture_with_timeout() {
  local seconds="$1"
  shift
  python3 - "$seconds" "$@" <<'PY'
import subprocess
import sys

timeout = float(sys.argv[1])
cmd = sys.argv[2:]

try:
    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        timeout=timeout,
        check=False,
    )
    sys.stdout.write(result.stdout)
except subprocess.TimeoutExpired:
    pass
PY
}

replace_managed_block() {
  local file="$1" begin="$2" end="$3" block="$4"
  run mkdir -p "$(dirname "$file")"
  if [ "${DRY_RUN:-0}" -eq 1 ]; then
    echo "DRY-RUN: replace managed block in $file"
    return 0
  fi
  if [ ! -f "$file" ]; then
    printf '%s\n' "$block" > "$file"
    return 0
  fi

  python3 - "$file" "$begin" "$end" "$block" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
begin, end, block = sys.argv[2], sys.argv[3], sys.argv[4]
text = path.read_text()
start = text.find(begin)
finish = text.find(end)
if start != -1 and finish != -1 and finish >= start:
    finish += len(end)
    while finish < len(text) and text[finish] == "\n":
        finish += 1
    prefix = text[:start].rstrip()
    suffix = text[finish:].lstrip("\n")
    parts = [part for part in (prefix, block.rstrip(), suffix.rstrip()) if part]
    text = "\n\n".join(parts) + "\n"
else:
    text = text.rstrip() + "\n\n" + block.rstrip() + "\n"
path.write_text(text)
PY
}

download_and_run() {
  local url="$1"; shift
  local script_path; script_path="$(mktemp)"
  run curl -fsSL "$url" -o "$script_path"
  run chmod +x "$script_path"
  run bash "$script_path" "$@"
  if [ "${DRY_RUN:-0}" -eq 0 ]; then rm -f "$script_path"; fi
}

pick_rtk_source() {
  if [ -f "$CLAUDE_RTK" ]; then
    printf '%s\n' "$CLAUDE_RTK"
  elif [ -f "$CODEX_RTK" ]; then
    printf '%s\n' "$CODEX_RTK"
  else
    printf '\n'
  fi
}

write_markdown_file() {
  local path="$1" body="$2"
  run mkdir -p "$(dirname "$path")"
  if [ "${DRY_RUN:-0}" -eq 1 ]; then
    echo "DRY-RUN: write markdown file $path"
  else
    printf '%s\n' "$body" > "$path"
  fi
}


write_managed_symlink() {
  local source="$1" target="$2"
  run mkdir -p "$(dirname "$target")"
  if [ "${DRY_RUN:-0}" -eq 1 ]; then
    echo "DRY-RUN: symlink $target -> $source"
    return 0
  fi
  if [ -L "$target" ]; then
    if [ "$(readlink "$target")" = "$source" ]; then
      echo "  LINK  $target -> $source"
      return 0
    fi
    local old_target="$(readlink "$target")"
    case "$old_target" in
      *12-rules.md|*/agent/rules/AGENTS.md|*/.claude/AGENTS.md|AGENTS.md)
        run rm -f "$target"
        ;;
      *)
        echo "  SKIP  $target exists as an unmanaged symlink"
        return 0
        ;;
    esac
  fi
  if [ -f "$target" ] && [ "$(basename "$target")" = "CLAUDE.md" ]; then
    local first_line
    first_line="$(head -n 1 "$target" 2>/dev/null || true)"
    if [ "$first_line" = "@12-rules.md" ] && grep -q "@adversarial-review-gate.md" "$target" 2>/dev/null; then
      run rm -f "$target"
    fi
  fi
  if [ -e "$target" ]; then
    if grep -q "Generated by install-agent-tooling.sh" "$target" 2>/dev/null; then
      run rm -f "$target"
    else
      echo "  SKIP  $target exists as unmanaged file"
      return 0
    fi
  fi
  run ln -s "$source" "$target"
}


ensure_file_contains() {
  local path="$1" needle="$2" addition="$3"
  run mkdir -p "$(dirname "$path")"
  if [ "${DRY_RUN:-0}" -eq 1 ]; then
    echo "DRY-RUN: ensure $path contains $needle"
    return 0
  fi
  if [ ! -f "$path" ]; then
    printf '%s\n' "$addition" > "$path"
    return 0
  fi
  if ! grep -Fq "$needle" "$path" 2>/dev/null; then
    printf '\n%s\n' "$addition" >> "$path"
  fi
}

CRG_BIN() { command -v codebase-memory-mcp 2>/dev/null; }
