#!/usr/bin/env python3
"""Render and verify managed global instructions without overwriting user content."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


BEGIN = "<!-- codex-global-instructions:start -->"
END = "<!-- codex-global-instructions:end -->"
LEGACY_REFERENCE = re.compile(r"^@.*(?:12-rules|RTK)\.md\s*$")


def managed_block(rules: Path, rtk: Path) -> str:
    return "\n".join(
        (
            BEGIN,
            "<!-- Generated by install-agent-tooling.sh; edit canonical sources, not this block. -->",
            rules.read_text().rstrip(),
            "",
            rtk.read_text().rstrip(),
            END,
        )
    )


def without_managed_block(text: str) -> str:
    start = text.find(BEGIN)
    finish = text.find(END, start + len(BEGIN)) if start >= 0 else -1
    if start >= 0 and finish >= start:
        finish += len(END)
        text = text[:start] + text[finish:]
    lines = [line for line in text.splitlines() if not LEGACY_REFERENCE.match(line)]
    return "\n".join(lines).strip()


def render(target: Path, rules: Path, rtk: Path) -> None:
    existing = target.read_text() if target.exists() else ""
    user_content = without_managed_block(existing)
    content = "\n\n".join(part for part in (managed_block(rules, rtk), user_content) if part)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content.rstrip() + "\n")


def verify(target: Path, rules: Path, rtk: Path) -> bool:
    if not target.is_file():
        return False
    text = target.read_text()
    expected = managed_block(rules, rtk)
    return text.count(BEGIN) == 1 and text.count(END) == 1 and expected in text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("render", "verify"))
    parser.add_argument("--target", required=True, type=Path)
    parser.add_argument("--rules", required=True, type=Path)
    parser.add_argument("--rtk", required=True, type=Path)
    args = parser.parse_args()

    if args.action == "render":
        render(args.target, args.rules, args.rtk)
        return 0
    return 0 if verify(args.target, args.rules, args.rtk) else 1


if __name__ == "__main__":
    raise SystemExit(main())
